//! download the optional cleanup model (a fine tuned qwen2.5-0.5b lora,
//! exported to fp32 onnx) from huggingface.
//!
//! the cleanup model polishes raw asr output (removes fillers, fixes
//! punctuation and casing) without paraphrasing. it is opt in: the bytes are
//! only fetched when the user asks, and inference is wired in a later
//! iteration. this module owns the asset set, the on disk directory, and the
//! pre download disk space check. streaming, verification, and progress are
//! shared with parakeet via `download.rs`.
//!
//! only the fp32 onnx is shipped. dynamic int8 was measured to collapse the
//! model (punctuation f1 0.571 -> 0.171), see models/cleanup/docs/model_report.md.

use anyhow::Result;
use std::path::Path;
use tauri::AppHandle;

use crate::download::{self, Asset, CancelFlag};

/// the human readable model name surfaced in the settings ui.
pub const CLEANUP_NAME: &str = "Mumble Cleanup (Qwen2.5-0.5B, fp32)";

/// sum of all asset sizes. drives the aggregate progress bar and the headline
/// "1.98 GB" size pill. kept in sync with the pinned assets by
/// models/cleanup/scripts/capture_hashes.py.
pub const TOTAL_BYTES: u64 = 1_993_125_193;

/// free space required before a download is allowed: the model plus headroom
/// for the in flight `.partial` files and filesystem slack.
pub const REQUIRED_DISK_BYTES: u64 = 2_500_000_000;

// generated by models/cleanup/scripts/capture_hashes.py against
// adikuma/mumble-cleanup. each digest is the sha256 of the exact bytes the hub
// serves; a changed upstream file fails the download rather than swapping the
// model.
const ASSETS: &[Asset] = &[
    Asset {
        url: "https://huggingface.co/adikuma/mumble-cleanup/resolve/main/onnx/model.onnx",
        filename: "model.onnx",
        sha256: "5138eaa57afa4bcf1b6335d2bab092cb72f1233f35b693a86811c38339142efd",
    },
    Asset {
        url: "https://huggingface.co/adikuma/mumble-cleanup/resolve/main/onnx/model.onnx_data",
        filename: "model.onnx_data",
        sha256: "05e879e01e222e19cf3e82d37bdf0a368fa361b94f3c3893656ae70faf3bd8ea",
    },
    Asset {
        url: "https://huggingface.co/adikuma/mumble-cleanup/resolve/main/config.json",
        filename: "config.json",
        sha256: "57c2bbb6c62915ad8900ca692a7c84d11ccb19f32aaf9c4150308f01b4557109",
    },
    Asset {
        url: "https://huggingface.co/adikuma/mumble-cleanup/resolve/main/generation_config.json",
        filename: "generation_config.json",
        sha256: "da7d43d773bb1c2606bbd062d9af2e8aa2b73de104b1f8f0a93e31bf3b1426a3",
    },
    Asset {
        url: "https://huggingface.co/adikuma/mumble-cleanup/resolve/main/tokenizer.json",
        filename: "tokenizer.json",
        sha256: "9c5ae00e602b8860cbd784ba82a8aa14e8feecec692e7076590d014d7b7fdafa",
    },
    Asset {
        url: "https://huggingface.co/adikuma/mumble-cleanup/resolve/main/tokenizer_config.json",
        filename: "tokenizer_config.json",
        sha256: "0a04a9d7d4a62b28482bdfe726c122756de85714fb64166ace92ae75b8f57614",
    },
    Asset {
        url: "https://huggingface.co/adikuma/mumble-cleanup/resolve/main/special_tokens_map.json",
        filename: "special_tokens_map.json",
        sha256: "76862e765266b85aa9459767e33cbaf13970f327a0e88d1c65846c2ddd3a1ecd",
    },
    Asset {
        url: "https://huggingface.co/adikuma/mumble-cleanup/resolve/main/vocab.json",
        filename: "vocab.json",
        sha256: "ca10d7e9fb3ed18575dd1e277a2579c16d108e32f27439684afa0e10b1440910",
    },
    Asset {
        url: "https://huggingface.co/adikuma/mumble-cleanup/resolve/main/merges.txt",
        filename: "merges.txt",
        sha256: "8831e4f1a044471340f7c0a83d7bd71306a5b867e95fd870f74d0c5308a904d5",
    },
    Asset {
        url: "https://huggingface.co/adikuma/mumble-cleanup/resolve/main/added_tokens.json",
        filename: "added_tokens.json",
        sha256: "58b54bbe36fc752f79a24a271ef66a0a0830054b4dfad94bde757d851968060b",
    },
    Asset {
        url: "https://huggingface.co/adikuma/mumble-cleanup/resolve/main/chat_template.jinja",
        filename: "chat_template.jinja",
        sha256: "cd8e9439f0570856fd70470bf8889ebd8b5d1107207f67a5efb46e342330527f",
    },
];

pub fn model_is_present(dir: &Path) -> bool {
    download::assets_present(dir, ASSETS)
}

pub async fn ensure_model(app: &AppHandle, dir: std::path::PathBuf, cancel: CancelFlag) -> Result<()> {
    if model_is_present(&dir) {
        return Ok(());
    }
    download::download_assets(
        app,
        &dir,
        ASSETS,
        "mumble://cleanup-download-progress",
        TOTAL_BYTES,
        Some(cancel),
    )
    .await
}

pub fn delete_model(dir: &Path) -> Result<()> {
    download::delete_assets(dir, ASSETS)
}

/// free bytes available on the volume that holds `dir`. used to gate the
/// download so a user with a near full disk is warned before 2 gb starts
/// streaming. on non windows dev hosts this returns `u64::MAX` so the check
/// never blocks frontend only smoke tests.
pub fn available_disk_bytes(dir: &Path) -> u64 {
    available_disk_bytes_impl(dir)
}

#[cfg(windows)]
fn available_disk_bytes_impl(dir: &Path) -> u64 {
    use windows::core::HSTRING;
    use windows::Win32::Storage::FileSystem::GetDiskFreeSpaceExW;

    // GetDiskFreeSpaceExW wants a directory that exists. walk up to the first
    // existing ancestor (the models dir may not be created yet).
    let mut probe = dir;
    while !probe.exists() {
        match probe.parent() {
            Some(parent) => probe = parent,
            None => return u64::MAX,
        }
    }

    let wide = HSTRING::from(probe.as_os_str());
    let mut free_available: u64 = 0;
    let ok = unsafe {
        GetDiskFreeSpaceExW(&wide, Some(&mut free_available), None, None)
    };
    match ok {
        Ok(()) => free_available,
        Err(e) => {
            tracing::warn!(?e, "GetDiskFreeSpaceExW failed, not blocking download");
            u64::MAX
        }
    }
}

#[cfg(not(windows))]
fn available_disk_bytes_impl(_dir: &Path) -> u64 {
    u64::MAX
}
